"""empty message

Revision ID: 6d4eebdbcadb
Revises: 5f0752ae5dc3
Create Date: 2024-06-04 18:16:24.271894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d4eebdbcadb'
down_revision = '5f0752ae5dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('Autorid', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Autorid')
    )
    op.create_table('written_by',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.Autorid'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.bookid'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('coverImage',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('coverImage',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('written_by')
    op.drop_table('authors')
    # ### end Alembic commands ###
